name: Cat Facts  

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  POST:

    runs-on: ubuntu-latest
    
    steps:
    - name: Grant execute permission for gradlew
      run: curl --location 'https://cat-fact.herokuapp.com/facts/'
